name: matchup
description: Una aplicación de citas y amistad para estudiantes universitarios
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management - BLoC
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^13.2.0

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.7

  # Utils
  equatable: ^2.0.5

  # Icons
  cupertino_icons: ^1.0.6

  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Permissions
  permission_handler: ^11.3.0

  # Location
  geolocator: ^10.1.0

  # File handling
  path_provider: ^2.1.2
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.0

  # BLoC Testing
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700